name: Backend Build and Test

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/API/requirements.txt

      - name: Display Python version and installed packages
        run: |
          python --version
          pip list

      - name: Run tests
        run: |
          pytest backend/API/tests

      - name: Debug if tests fail
        if: failure()
        run: |
          pwd
          ls -R
          which python
          which pytest
